### ISSUE TITLE
[BUG] Duplicate QRCodes

### ISSUE THREAD

**Issue by Siddharth-Chhatbar** [CMPUT301W23T14/QRHunter-App#96] opened 2023-03-31 02:04 UTC
**Describe the bug**
Users can scan the qrCode form the same location multiple times 

**To Reproduce**
Scan the same qrCode twice

**Expected behavior**
Give a toast or a prompt to the user that they have already scanned this qrCode and the latest scan was not added.

**Additional context**
1st Scan of the QRCode
<img width="451" alt="Before" src="https://user-images.githubusercontent.com/112894386/229003878-9d657666-d97e-431f-ba85-bef72f39abb9.png">

![before](https://user-images.githubusercontent.com/112894386/229003961-c72379b6-e0b1-4ce5-8974-2c0ac9b2cef8.png)

Scanning the qrCode 2nd time we can see that the score is updated but everything else remains the same
<img width="452" alt="after" src="https://user-images.githubusercontent.com/112894386/229004122-a4989761-f2ef-424c-aaad-513a4d75e277.png">
![after](https://user-images.githubusercontent.com/112894386/229004138-5d7ba0f4-9b76-4008-b16c-c884e41731b1.png)

**Comment by MaxxonTan** [comment] 2023-03-31 12:57
AHhh okay I know what the problem is, should be a small fix. I'll assign this to myself

**Closed** 2023-04-01 04:27 UTC
Labels: bug
